#!/bin/sh

NAME="curl"
VERSION="7.62.0"
LICENSE="MIT"
DESCRIPTION="A Tool for Transferring Data from URLs."
RUNDEPS="ca-certificates"
MAKEDEPS="libc libressl libz"

SRC="${NAME}-${VERSION}"
URL="https://curl.haxx.se/download/${NAME}-${VERSION}.tar.gz"
INFILE="../curl.in"

. ${PORTS}/mk/indef.sh

Build() {
	cp mk/curl_config.h "${SRC}/lib"
	( __default_build )
}

$@
