#!/bin/sh

NAME=""
LONGNAME=""
VERSION=""
LICENSE=""
DESCRIPTION=""
RUNDEPS=""
MAKEDEPS=""

SRC=""
URL=""
GIT=""
INFILE=""
PATCHES=""

. ${PORTS}/mk/default.sh

prepare() {
}

build() {
}

install() {
}

$@
