#!/bin/sh

NAME=""
VERSION=""
LICENSE=""
DESCRIPTION=""
RUNDEPS=""
MAKEDEPS=""

SRC=""
URL=""
GIT=""
INFILE=""
PATCHES=""

# Replace "*" with the build system (in,auto)
. ${PORTS}/mk/*def.sh

# "*def.sh" includes the functions below, but for specific behaviour
# may be necessary to redefine them.
Prepare() {
}

Build() {
}

Install() {
}

Package() {
}

$@
