#!/bin/dash

NAME="bzip2"
LONGNAME="$NAME"
VERSION="1.0.6"
LICENSE="BSD"
DESCRIPTION="Is a high-quality data compressor."
MAKEDEPS="libc"

SRC="${NAME}-${VERSION}"
URL="http://www.bzip.org/1.0.6/${NAME}-${VERSION}.tar.gz"
INFILE="../bzip2.in"

. ${PORTS}/mk/default.sh

prepare() {
	default_prepare
}

build() {
	default_build
}

install() {
	true
}

$@
