<$PORTS/mk/mk.3rd

NAME     = bzip2
VERSION  = 1.0.6
LICENSE  = BSD
DESCRIPTION = bzip2 is a high-quality data compressor.

MAKEDEPS = libc

SRC = ${NAME}-${VERSION}
URL = http://www.bzip.org/1.0.6/${NAME}-${VERSION}.tar.gz
MKFILE = ../bzip2.mk
