#!/bin/sh

NAME="bzip2"
VERSION="1.0.6"
LICENSE="BSD"
DESCRIPTION="Is a high-quality data compressor."
MAKEDEPS="libc"

SRC="${NAME}-${VERSION}"
URL="http://www.bzip.org/1.0.6/${NAME}-${VERSION}.tar.gz"
INFILE="../bzip2.in"

. ${PORTS}/mk/default.sh

Prepare() {
	default_prepare
}

Build() {
	default_build
}

Install() {
	default_install
}

Package() {
	default_package
}

$@
