#!/bin/sh

NAME="bzip2"
VERSION="1.0.6"
LICENSE="BSD"
DESCRIPTION="Is a high-quality data compressor."
MAKEDEPS="libc"

SRC="$NAME"
GIT="https://github.com/eadwardus/$NAME"
INFILE="../bzip2.in"

. ${PORTS}/mk/indef.sh

$@
