<$PORTSmk/mk.3rd

NAME    = mksh
VERSION = 56b
LICENSE = MIROS
DESCRIPTION = MirBSD Korn Shell - an enhanced version of the public domain ksh.

MAKEDEPS = libc

SRC = $NAME
URL = https://www.mirbsd.org/MirOS/dist/mir/mksh/${NAME}-R${VERSION}.tgz
MKFILE = ../mksh.mk
