#!/bin/sh
#NONDBUILD

NAME="mksh"
VERSION="56c"
LICENSE="MIROS"
DESCRIPTION="An enhanced version of the public domain ksh."
MAKEDEPS="libc"

SRC="$NAME"
URL="https://www.mirbsd.org/MirOS/dist/mir/mksh/${NAME}-R${VERSION}.tgz"
INFILE="../mksh.in"

. ${PORTS}/mk/indef.sh

Build() {
	( cd "$SRC"
	chmod +x Build.sh
	( mkdir build_mksh
	cd build_mksh
	../Build.sh -r )
	( mkdir build_lksh
	cd build_lksh
	env CPPFLAGS="-DMKSH_BINSHPOSIX -DMKSH_BINSHREDUCED -DMKSH_SMALL -DMKSH_LEGACY"\
	    ../Build.sh -L -r )
	$COMPRESS lksh.1 mksh.1 )
}

Install() {
	( binaries="build_mksh/mksh build_lksh/lksh"
	manpages="lksh.1 mksh.1"
	__default_install )
}

$@
