#!/bin/sh

NAME="mksh"
LONGNAME="$NAME"
VERSION="56b"
LICENSE="MIROS"
DESCRIPTION="An enhanced version of the public domain ksh."
MAKEDEPS="libc"

SRC="$NAME"
URL="https://www.mirbsd.org/MirOS/dist/mir/mksh/${NAME}-R${VERSION}.tgz"
INFILE="../mksh.in"

. ${PORTS}/mk/default.sh

Prepare() {
	default_prepare
	chmod +x Build.sh
	./Build.sh -r -M
	env srcfile="rlimits.opt"  BUILDSH_RUN_GENOPT=1 ./Build.sh
	env srcfile="sh_flags.opt" BUILDSH_RUN_GENOPT=1 ./Build.sh
}

Build() {
	default_build
}

Install() {
	default_install
}

Package() {
	default_package
}

$@
