<$PORTS/mk/mk.3rd

NAME     = pkgconfig
LONGNAME = pkgconf
VERSION  = 1.3.10
LICENSE  = custom-ISC
DESCRIPTION = A program which helps to configure compiler and linker flags\
 for development frameworks.

MAKEDEPS = libc

SRC = ${NAME}-${VERSION}
URL = https://distfiles.dereferenced.org/pkgconf/${NAME}-${VERSION}.tar.gz
MKFILE = ../pkgconf.mk
