#!/bin/sh

NAME="samurai"
LONGNAME="$NAME"
VERSION="git-master"
LICENSE="ISC"
DESCRIPTION="A ninja-compatible build tool written in C."
MAKEDEPS="libc"

SRC="$NAME"
GIT="https://github.com/michaelforney/samurai"
INFILE="../samurai.in"

. ${PORTS}/mk/default.sh

Prepare() {
	default_prepare
}

Build() {
	default_build
}

Install() {
	default_install
}

Package() {
	default_package
}

$@
