#!/bin/sh

NAME="samurai"
VERSION="0.4"
LICENSE="ISC"
DESCRIPTION="A ninja-compatible build tool written in C."
MAKEDEPS="libc"

SRC="$NAME"
GIT="https://github.com/michaelforney/samurai"
INFILE="../samurai.in"

. ${PORTS}/mk/indef.sh

# Samurai doesn't use the standard "v${VERSION}" tag name
Prepare() {
	if [ ! -d "$SRC" ]; then
		git clone "$GIT" "$SRC"
		( cd "$SRC"
		[ "$VERSION" == "master" ] || git checkout tags/${VERSION} \
		  && printf "git-$(git rev-parse HEAD)" > ../._mk_v )
	fi
	__apply_patches
}

$@
