#!/bin/sh

NAME="samurai"
VERSION="0.3"
BRANCH="$VERSION"
LICENSE="ISC"
DESCRIPTION="A ninja-compatible build tool written in C."
MAKEDEPS="libc"

SRC="$NAME"
GIT="https://github.com/michaelforney/samurai"
INFILE="../samurai.in"

. ${PORTS}/mk/indef.sh

$@
