.Dd $Mdocdate: June 02 2021 $
.Dt MKUTILS 1
.Os
.Sh NAME
.Nm mkutils
.Nd portsys utilities
.Sh SYNOPSIS
.Nm
.Ar command
.Ar args ...
.Sh DESCRIPTION
The
.Nm
utility executes
.Ar command
with the given
.Ar args .
.Ss COMMANDS
.Bl -tag -width
.It Cm env Ar command
Executes
.Ar command
with the portsys environment.
.It Cm install Bro Cm bin | drt | inc | lib | man Brc Oo Fl d | Fl e | l | r Oc Ar
Copy files according to its category.
.Bl -tag -width Ds -compact
.It Fl d
Delete files instead of copying.
.It Fl e
Create empty files.
.It Fl l
Create symbolic links
.It Fl r
Copy directories recursively.
.El
.It Cm sed Ar file args ...
Executes the system sed and replaces the
.Ar file
atomically.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr portsys 1 ,
.Xr portmk 1
