.Dd $Mdocdate: January 12 2020 $
.Dt PORTSYS 1
.Os
.Sh NAME
.Nm portsys
.Nd build system
.Sh SYNOPSIS
.Nm
.Cm operation
.Op Fl ADk
.Op Fl depr Ar dir
.Ar port ...
.Sh DESCRIPTION
The
.Nm
utility executes the set operation for each
.Ar port
entry.
.Ss Operations
.Bl -tag -width
.It Cm install
Install the port to the root system and add an entry to the local database.
.It Cm package
Creates a port package under
.Ev $PORTS Ns /portsys_pkgs .
The files are archived with
.Xr venus-ar 1
and compressed with
.Xr lzip 1 .
.El
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl A
Copy all files.
.It Fl D
Copy only development files.
.It Fl d Ar dir
Set
.Ar dir
as cache directory.
.It Fl e Ar dir
Search
.Ar dir
for headers and libraries.
.It Fl k
Operate dependencies as if given explicitly.
.It Fl p Ar dir
Set
.Ar dir
as target for generated packages.
.It Fl r Ar dir
Set
.Ar dir
as root system.
.El
.Pp
If the
.Fl A
and
.Fl D
options are not specified,
.Nm
will not copy development files.
.Sh ENVIRONMENT
.Bl -tag -width PORTS
.It Ev PORTS
Set the path where ports is found.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr venus 1 ,
.Xr venus-ar 1
