#!/bin/sh
#NONDBUILD

NAME="netbsd-ncurses"
VERSION="0.2.1"
LICENSE="BSD-3"
DESCRIPTION="Netbsd curses library."
MAKEDEPS="libc"

SRC="${NAME}-${VERSION}"
URL="http://ftp.barfooze.de/pub/sabotage/tarballs/${NAME}-${VERSION}.tar.xz"
INFILE="../ncurses.in"

. ${PORTS}/mk/autodef.sh

$@
