#!/bin/sh
#NONDBUILD

NAME="ncurses"
LONGNAME="netbsd-curses"
VERSION="0.2.1"
LICENSE="BSD-3"
DESCRIPTION="Netbsd curses library."
MAKEDEPS="libc"

SRC="${LONGNAME}-${VERSION}"
URL="http://ftp.barfooze.de/pub/sabotage/tarballs/${LONGNAME}-${VERSION}.tar.xz"
INFILE="../ncurses.in"

. ${PORTS}/mk/default.sh

Prepare() {
	default_prepare
}

Build() {
	cd $SRC
	make CC="$CC" CFLAGS="$CPPFLAGS $CFLAGS" LDFLAGS="$LDFLAGS" all-static
}

Install() {
	true
}

$@
