#!/bin/sh
#NONDBUILD

NAME="ncurses"
VERSION="0.2.2"
LICENSE="BSD-3"
DESCRIPTION="A NetBSD curses library."
MAKEDEPS="libc"

SRC="netbsd-curses-${VERSION}"
URL="http://ftp.barfooze.de/pub/sabotage/tarballs/netbsd-curses-${VERSION}.tar.xz"
INFILE="../ncurses.in"

. ${PORTS}/mk/indef.sh

Build() {
	( cd "$SRC"
	cat <<-EOF > config.mak
	CFLAGS=$CFLAGS
	CPPFLAGS=$CPPFLAGS
	LDFLAGS=$LDFLAGS
	PREFIX=$PREFIX
	EOF
	make all-static )
}

Install() {
	( cd "$SRC"
	make DESTDIR="$ROOT" install-static )
}

$@
