<$PORTSmk/mk.3rd

NAME    = libressl
VERSION = 2.6.2
LICENSE = OPENSSL
DESCRIPTION = LibreSSL is a fork of, and drop in replacement for OpenSSL.

MAKEDEPS= libc linux-headers


SRC = $NAME-$VERSION
URL = https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/${NAME}-${VERSION}.tar.gz
MKFILE = ../libressl.mk
