#!/bin/sh
#NONDBUILD

NAME="libressl"
VERSION="2.7.2"
LICENSE="OPENSSL"
DESCRIPTION="Is a fork of, and drop in replacement for OpenSSL."
MAKEDEPS="libc linux-headers"

SRC="${NAME}-${VERSION}"
URL="https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/${NAME}-${VERSION}.tar.gz"

. ${PORTS}/mk/autodef.sh

$@
