<$PORTS/mk/mk.3rd

NAME     = cbase
VERSION  = 0.0
LICENSE  = MULTIPLE
DESCRIPTION = Complementary set of unix utilities for utilchest.

MAKEDEPS = libc ncurses

SRC = $NAME
GIT = https://github.com/eltanin-os/$NAME
MKFILE = ../cbase.mk
