#!/bin/sh

NAME="cbase"
VERSION="master"
LICENSE="MULTIPLE"
DESCRIPTION="Complementary set of unix utilities for utilchest."
MAKEDEPS="libc ncurses"

SRC="$NAME"
GIT="https://github.com/eltanin-os/$NAME"
INFILE="../cbase.in"

. ${PORTS}/mk/indef.sh

$@
