<$PORTS/mk/mk.3rd

NAME     = dash
VERSION  = 0.5.9
LICENSE  = BSD-3
DESCRIPTION = A POSIX compliant shell that aims to be as small as possible.

MAKEDEPS = libc

SRC = $NAME-$VERSION
URL = http://gondor.apana.org.au/~herbert/dash/files/${NAME}-${VERSION}.tar.gz
MKFILE = ../dash.mk
