#!/bin/sh
#NONDBUILD

NAME="dash"
VERSION="0.5.9.1"
LICENSE="BSD-3"
DESCRIPTION="A POSIX compliant shell that aims to be as small as possible."
MAKEDEPS="libc"

SRC="${NAME}-${VERSION}"
URL="http://gondor.apana.org.au/~herbert/dash/files/${NAME}-${VERSION}.tar.gz"

. ${PORTS}/mk/autodef.sh

$@
