#!/bin/sh

NAME="utilchest"
LONGNAME="$NAME"
VERSION="0"
LICENSE="UNLICENSE"
DESCRIPTION="A set of unix utilities written to be simple and small."
MAKEDEPS="libc"

SRC="$NAME"
GIT="https://github.com/eltanin-os/$NAME"
INFILE="../utilchest.in"

. ${PORTS}/mk/default.sh

prepare() {
	default_prepare
}

build() {
	default_build
}

install() {
	true
}

$@
