<$PORTS/mk/build.mk
# ABOUT
NAME    = utilchest
VERSION = 0
LICENSE = UNLICENSE
DESCRIPTION = A set of unix utilities

MAKEDEPS= libc

# RULES
SRC = utilchest
GIT = https://github.com/eltanin-os/utilchest
MKFILE = ../utilchest.mk
