<$PORTS/mk/mk.3rd

NAME    = utilchest
VERSION = 0
LICENSE = UNLICENSE
DESCRIPTION = A set of unix utilities.

MAKEDEPS= libc

SRC = $NAME
GIT = https://github.com/eltanin-os/$NAME
MKFILE = ../utilchest-box.mk

# utilchest in multiple binaries
# MKFILE = ../utilchest.mk
