<$PORTS/mk/mk.3rd

NAME    = utilchest
VERSION = 0
LICENSE = UNLICENSE
DESCRIPTION = A set of unix utilities written to be simple and small.

MAKEDEPS= libc

SRC = $NAME
GIT = https://github.com/eltanin-os/$NAME
INFILE = ../utilchest.in

# utilchest in a single binary
#MKFILE = ../utilchest-box.mk
