#!/bin/sh
#Uncomment line 13 and comment lines 12, 16 and 20 for separated binaries.
NAME="utilchest"
LONGNAME="$NAME"
VERSION="0"
LICENSE="UNLICENSE"
DESCRIPTION="A set of unix utilities written to be simple and small."
MAKEDEPS="libc"

SRC="$NAME"
GIT="https://github.com/eltanin-os/$NAME"
INFILE="../utilchest-box.in"
#INFILE="../utilchest.in"

. ${PORTS}/mk/default.sh
. extra/box.sh

Prepare() {
	default_prepare
	prepare_box
}

Build() {
	default_build
}

Install() {
	default_install LIBS
}

Package() {
	default_package
}

$@
