#!/bin/sh

NAME="utilchest"
LONGNAME="$NAME"
VERSION="0"
LICENSE="UNLICENSE"
DESCRIPTION="A set of unix utilities written to be simple and small."
MAKEDEPS="libc"

SRC="$NAME"
GIT="https://github.com/eltanin-os/$NAME"
INFILE="../utilchest.in"

. ${PORTS}/mk/default.sh

Prepare() {
	default_prepare
}

Build() {
	default_build
}

Install() {
	default_install LIBS
}

Package() {
	default_package
}

$@
