<$PORTS/mk/mk.3rd

NAME     = mandoc
VERSION  = 1.14.3
LICENSE  = ISC
DESCRIPTION = A suite of tools compiling mdoc from the OpenBSD project.

MAKEDEPS = libc

SRC = ${NAME}-${VERSION}
URL = http://mdocml.bsd.lv/snapshots/${NAME}-${VERSION}.tar.gz
MKFILE = ../mandoc.mk
