#!/bin/sh

NAME="mandoc"
VERSION="1.14.3"
LICENSE="ISC"
DESCRIPTION="A suite of tools compiling mdoc from the OpenBSD project."
MAKEDEPS="libc zlib"

SRC="${NAME}-${VERSION}"
URL="http://mdocml.bsd.lv/snapshots/${NAME}-${VERSION}.tar.gz"
INFILE="../mandoc.in"

. ${PORTS}/mk/default.sh

Prepare() {
	default_prepare
	cp ../buildext/config.h .
}

Build() {
	default_build
}

Install() {
	default_install
}

Package() {
	default_package
}

$@
