<$PORTS/mk/mk.3rd

NAME     = pigz
VERSION  = 2.3.4
LICENSE  = zlib
DESCRIPTION = Parallel implementation of the gzip file compressor.

MAKEDEPS = libc

SRC = ${NAME}-${VERSION}
URL = https://zlib.net/pigz/${NAME}-${VERSION}.tar.gz
MKFILE = ../pigz.mk
