#!/bin/sh

NAME="pigz"
VERSION="2.4"
LICENSE="zlib"
DESCRIPTION="Parallel implementation of the gzip file compressor."
RUNDEPS="libc zlib"

SRC="${NAME}-${VERSION}"
URL="https://zlib.net/pigz/${NAME}-${VERSION}.tar.gz"
INFILE="../pigz.in"

. ${PORTS}/mk/indef.sh

$@
