#!/bin/sh

NAME="libz"
VERSION="1.2.8.2015.12.26"
LICENSE="zlib"
DESCRIPTION="An ABI-compatible and API-compatible drop-in replacement for zlib."
MAKEDEPS="libc"

SRC="${NAME}-${VERSION}"
URL="https://sortix.org/libz/release/${NAME}-${VERSION}.tar.gz"
INFILE="../libz.in"

. ${PORTS}/mk/indef.sh

$@
