#!/bin/sh

NAME="pigz"
VERSION="2.4"
LICENSE="zlib"
DESCRIPTION="Parallel implementation of the gzip file compressor."
RUNDEPS="libc libz"

SRC="${NAME}-${VERSION}"
URL="https://zlib.net/pigz/${NAME}-${VERSION}.tar.gz"
INFILE="../pigz.in"

. ${PORTS}/mk/indef.sh

$@
[vars]
name=pigz
version=2.4
license=zlib
description=Parallel implementation of the gzip file compressor.
cksum=79b2357176f93b9f3e2bc07fee393fc4d79b7bd0041808f8ddfd23eafccde72e60ca95e97595bb624a4f732fe3612bf46d57c44541c36ae62f9aa6336abe16ba

[mirrors]
ttps://zlib.net/pigz/${name}-${version}.tar.gz

[mdeps]
libc
libz

[build]
make

[install]
make install
